<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace tink\core\_Promise;

use \tink\core\_Future\SyncFuture;
use \php\Boot;
use \tink\core\Outcome;
use \tink\core\_Lazy\LazyConst;

final class Combiner_Impl_ {
	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofSafe ($f) {
		return function ($x1, $x2) use (&$f) {
			return new SyncFuture(new LazyConst($f($x1, $x2)));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofSafeSync ($f) {
		return function ($x1, $x2) use (&$f) {
			return new SyncFuture(new LazyConst(Outcome::Success($f($x1, $x2))));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofSync ($f) {
		return function ($x1, $x2) use (&$f) {
			return $f($x1, $x2)->map(Boot::getStaticClosure(Outcome::class, 'Success'))->gather();
		};
	}
}

Boot::registerClass(Combiner_Impl_::class, 'tink.core._Promise.Combiner_Impl_');
