<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace datetime\utils\pack;

use \php\Boot;

/**
 * Time period in timezone data
 *
 */
interface IPeriod {
	/**
	 * Get time offset at the first second of this period
	 *
	 * 
	 * @return int
	 */
	public function getStartingOffset () ;

	/**
	 * Get period from one time switch to another switch, which contains `utc`
	 *
	 * 
	 * @param float $utc
	 * 
	 * @return TZPeriod
	 */
	public function getTZPeriod ($utc) ;

	/**
	 * Get string representation of this period
	 *
	 * 
	 * @return string
	 */
	public function toString () ;
}

Boot::registerClass(IPeriod::class, 'datetime.utils.pack.IPeriod');
