<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace datetime\utils\pack;

use \php\Boot;

/**
 * Timezone abbreviation structure for encoding timezones
 *
 */
class TZAbr {
	/**
	 * @var int
	 * abbreviation index in abbreviations dictionary
	 */
	public $idx;
	/**
	 * @var string
	 * abbreviation
	 */
	public $name;

	/**
	 * Constructor
	 *
	 * 
	 * @param string $name
	 * @param int $idx
	 * 
	 * @return void
	 */
	public function __construct ($name, $idx) {
		$this->name = $name;
		$this->idx = $idx;
	}
}

Boot::registerClass(TZAbr::class, 'datetime.utils.pack.TZAbr');
