<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\http\_StructuredBody;

use \php\_Boot\HxAnon;
use \php\Boot;
use \tink\core\Noise;
use \tink\io\_Source\Source_Impl_;
use \tink\streams\Single;
use \tink\core\TypedError;
use \sys\io\File;
use \tink\chunk\ByteChunk;
use \tink\core\Outcome;
use \tink\core\_Lazy\LazyConst;
use \tink\io\_Sink\SinkYielding_Impl_;
use \haxe\io\Bytes;

final class UploadedFile_Impl_ {
	/**
	 * @param string $name
	 * @param string $type
	 * @param Bytes $data
	 * 
	 * @return object
	 */
	public static function ofBlob ($name, $type, $data) {
		return new HxAnon([
			"fileName" => $name,
			"mimeType" => $type,
			"size" => $data->length,
			"read" => function () use (&$data) {
				return new Single(new LazyConst(ByteChunk::of($data)));
			},
			"saveTo" => function ($path) use (&$data) {
				$dest = SinkYielding_Impl_::ofOutput("File sink " . ($path??'null'), File::write($path));
				return Source_Impl_::pipeTo(new Single(new LazyConst(ByteChunk::of($data))), $dest, new HxAnon(["end" => true]))->map(function ($r) {
					$__hx__switch = ($r->index);
					if ($__hx__switch === 0) {
						return Outcome::Success(Noise::Noise());
					} else if ($__hx__switch === 1) {
						return Outcome::Failure(new TypedError(null, "File \$path closed unexpectedly", new HxAnon([
							"fileName" => "tink/http/StructuredBody.hx",
							"lineNumber" => 37,
							"className" => "tink.http._StructuredBody.UploadedFile_Impl_",
							"methodName" => "ofBlob",
						])));
					} else if ($__hx__switch === 2) {
						return Outcome::Failure($r->params[0]);
					}
				})->gather();
			},
		]);
	}
}

Boot::registerClass(UploadedFile_Impl_::class, 'tink.http._StructuredBody.UploadedFile_Impl_');
