<?php
/**
 * Generated by Haxe 4.0.5
 */

namespace haxe\ds\_HashMap;

use \php\Boot;
use \haxe\ds\IntMap;

class HashMapData {
	/**
	 * @var IntMap
	 */
	public $keys;
	/**
	 * @var IntMap
	 */
	public $values;

	/**
	 * @return void
	 */
	public function __construct () {
		#C:\Program Files\Haxe\haxe\std/haxe/ds/HashMap.hx:108: characters 3-22
		$this->keys = new IntMap();
		#C:\Program Files\Haxe\haxe\std/haxe/ds/HashMap.hx:109: characters 3-24
		$this->values = new IntMap();
	}
}

Boot::registerClass(HashMapData::class, 'haxe.ds._HashMap.HashMapData');
