<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace haxe\xml\_Access;

use \php\Boot;
use \haxe\Exception;
use \_Xml\XmlType_Impl_;
use \haxe\xml\Printer;
use \haxe\iterators\ArrayIterator;

final class Access_Impl_ {

	/**
	 * @param \Xml $x
	 * 
	 * @return \Xml
	 */
	public static function _new ($x) {
		if (($x->nodeType !== \Xml::$Document) && ($x->nodeType !== \Xml::$Element)) {
			throw Exception::thrown("Invalid nodeType " . ((($x->nodeType === null ? "null" : XmlType_Impl_::toString($x->nodeType)))??'null'));
		}
		return $x;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_att ($this1) {
		return $this1;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return object
	 */
	public static function get_elements ($this1) {
		return $this1->elements();
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_has ($this1) {
		return $this1;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_hasNode ($this1) {
		return $this1;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return string
	 */
	public static function get_innerData ($this1) {
		if (($this1->nodeType !== \Xml::$Document) && ($this1->nodeType !== \Xml::$Element)) {
			throw Exception::thrown("Bad node type, expected Element or Document but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
		}
		$it = new ArrayIterator($this1->children);
		if (!$it->hasNext()) {
			$tmp = null;
			if ($this1->nodeType === \Xml::$Document) {
				$tmp = "Document";
			} else {
				if ($this1->nodeType !== \Xml::$Element) {
					throw Exception::thrown("Bad node type, expected Element but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
				}
				$tmp = $this1->nodeName;
			}
			throw Exception::thrown(($tmp??'null') . " does not have data");
		}
		$v = $it->next();
		if ($it->hasNext()) {
			$n = $it->next();
			$tmp = null;
			if (($v->nodeType === \Xml::$PCData) && ($n->nodeType === \Xml::$CData)) {
				if (($v->nodeType === \Xml::$Document) || ($v->nodeType === \Xml::$Element)) {
					throw Exception::thrown("Bad node type, unexpected " . ((($v->nodeType === null ? "null" : XmlType_Impl_::toString($v->nodeType)))??'null'));
				}
				$tmp = \trim($v->nodeValue) === "";
			} else {
				$tmp = false;
			}
			if ($tmp) {
				if (!$it->hasNext()) {
					if (($n->nodeType === \Xml::$Document) || ($n->nodeType === \Xml::$Element)) {
						throw Exception::thrown("Bad node type, unexpected " . ((($n->nodeType === null ? "null" : XmlType_Impl_::toString($n->nodeType)))??'null'));
					}
					return $n->nodeValue;
				}
				$n2 = $it->next();
				$tmp = null;
				if ($n2->nodeType === \Xml::$PCData) {
					if (($n2->nodeType === \Xml::$Document) || ($n2->nodeType === \Xml::$Element)) {
						throw Exception::thrown("Bad node type, unexpected " . ((($n2->nodeType === null ? "null" : XmlType_Impl_::toString($n2->nodeType)))??'null'));
					}
					$tmp = \trim($n2->nodeValue) === "";
				} else {
					$tmp = false;
				}
				if ($tmp && !$it->hasNext()) {
					if (($n->nodeType === \Xml::$Document) || ($n->nodeType === \Xml::$Element)) {
						throw Exception::thrown("Bad node type, unexpected " . ((($n->nodeType === null ? "null" : XmlType_Impl_::toString($n->nodeType)))??'null'));
					}
					return $n->nodeValue;
				}
			}
			$tmp = null;
			if ($this1->nodeType === \Xml::$Document) {
				$tmp = "Document";
			} else {
				if ($this1->nodeType !== \Xml::$Element) {
					throw Exception::thrown("Bad node type, expected Element but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
				}
				$tmp = $this1->nodeName;
			}
			throw Exception::thrown(($tmp??'null') . " does not only have data");
		}
		if (($v->nodeType !== \Xml::$PCData) && ($v->nodeType !== \Xml::$CData)) {
			$tmp = null;
			if ($this1->nodeType === \Xml::$Document) {
				$tmp = "Document";
			} else {
				if ($this1->nodeType !== \Xml::$Element) {
					throw Exception::thrown("Bad node type, expected Element but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
				}
				$tmp = $this1->nodeName;
			}
			throw Exception::thrown(($tmp??'null') . " does not have data");
		}
		if (($v->nodeType === \Xml::$Document) || ($v->nodeType === \Xml::$Element)) {
			throw Exception::thrown("Bad node type, unexpected " . ((($v->nodeType === null ? "null" : XmlType_Impl_::toString($v->nodeType)))??'null'));
		}
		return $v->nodeValue;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return string
	 */
	public static function get_innerHTML ($this1) {
		$s = new \StringBuf();
		if (($this1->nodeType !== \Xml::$Document) && ($this1->nodeType !== \Xml::$Element)) {
			throw Exception::thrown("Bad node type, expected Element or Document but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
		}
		$_this = $this1->children;
		$_g_current = 0;
		while ($_g_current < $_this->length) {
			$s->add(Printer::print(($_this->arr[$_g_current++] ?? null)));
		}
		return $s->b;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return string
	 */
	public static function get_name ($this1) {
		if ($this1->nodeType === \Xml::$Document) {
			return "Document";
		} else {
			if ($this1->nodeType !== \Xml::$Element) {
				throw Exception::thrown("Bad node type, expected Element but found " . ((($this1->nodeType === null ? "null" : XmlType_Impl_::toString($this1->nodeType)))??'null'));
			}
			return $this1->nodeName;
		}
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_node ($this1) {
		return $this1;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_nodes ($this1) {
		return $this1;
	}

	/**
	 * @param \Xml $this
	 * 
	 * @return \Xml
	 */
	public static function get_x ($this1) {
		return $this1;
	}
}

Boot::registerClass(Access_Impl_::class, 'haxe.xml._Access.Access_Impl_');
Boot::registerGetters('haxe\\xml\\_Access\\Access_Impl_', [
	'elements' => true,
	'hasNode' => true,
	'has' => true,
	'att' => true,
	'nodes' => true,
	'node' => true,
	'innerHTML' => true,
	'innerData' => true,
	'name' => true,
	'x' => true
]);
