<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\streams\_Stream;

use \tink\streams\StreamBase;
use \tink\core\_Future\SyncFuture;
use \php\Boot;
use \tink\streams\Step;
use \tink\core\TypedError;
use \tink\core\_Lazy\LazyConst;
use \tink\streams\Conclusion;
use \tink\core\FutureObject;

class ErrorStream extends StreamBase {
	/**
	 * @var TypedError
	 */
	public $error;

	/**
	 * @param TypedError $error
	 * 
	 * @return void
	 */
	public function __construct ($error) {
		parent::__construct();
		$this->error = $error;
	}

	/**
	 * @param \Closure $handler
	 * 
	 * @return FutureObject
	 */
	public function forEach ($handler) {
		return new SyncFuture(new LazyConst(Conclusion::Failed($this->error)));
	}

	/**
	 * @return FutureObject
	 */
	public function next () {
		return new SyncFuture(new LazyConst(Step::Fail($this->error)));
	}
}

Boot::registerClass(ErrorStream::class, 'tink.streams._Stream.ErrorStream');
