<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\streams\_Stream;

use \tink\core\_Future\SyncFuture;
use \php\Boot;
use \tink\streams\ReductionStep;
use \tink\core\_Lazy\LazyConst;
use \tink\core\FutureObject;

final class Reducer_Impl_ {
	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function _new ($f) {
		return $f;
	}

	/**
	 * @param \Closure $this
	 * @param mixed $res
	 * @param mixed $item
	 * 
	 * @return FutureObject
	 */
	public static function apply ($this1, $res, $item) {
		return $this1($res, $item);
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofPlainSync ($f) {
		return function ($res, $cur) use (&$f) {
			return new SyncFuture(new LazyConst(ReductionStep::Progress($f($res, $cur))));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofPromiseBased ($f) {
		return function ($res, $cur) use (&$f) {
			return $f($res, $cur)->map(function ($s) {
				$__hx__switch = ($s->index);
				if ($__hx__switch === 0) {
					return ReductionStep::Progress($s->params[0]);
				} else if ($__hx__switch === 1) {
					return ReductionStep::Crash($s->params[0]);
				}
			})->gather();
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofSafe ($f) {
		return $f;
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofSafeSync ($f) {
		return function ($res, $cur) use (&$f) {
			return new SyncFuture(new LazyConst($f($res, $cur)));
		};
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofUnknown ($f) {
		return $f;
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return \Closure
	 */
	public static function ofUnknownSync ($f) {
		return function ($res, $cur) use (&$f) {
			return new SyncFuture(new LazyConst($f($res, $cur)));
		};
	}
}

Boot::registerClass(Reducer_Impl_::class, 'tink.streams._Stream.Reducer_Impl_');
