<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\chunk;

use \php\Boot;

class ChunkIterator {
	/**
	 * @var bool
	 */
	public $_hasNext;
	/**
	 * @var ChunkCursor
	 */
	public $target;

	/**
	 * @param ChunkCursor $target
	 * 
	 * @return void
	 */
	public function __construct ($target) {
		$this->target = $target;
		$this->_hasNext = $target->length > $target->currentPos;
	}

	/**
	 * @return bool
	 */
	public function hasNext () {
		return $this->_hasNext;
	}

	/**
	 * @return int
	 */
	public function next () {
		$ret = $this->target->currentByte;
		$this->_hasNext = $this->target->next();
		return $ret;
	}
}

Boot::registerClass(ChunkIterator::class, 'tink.chunk.ChunkIterator');
