<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\http;

use \php\Boot;
use \tink\streams\StreamObject;

class Chunked {
	/**
	 * @var ChunkedDecoder
	 */
	static public $_decoder;
	/**
	 * @var ChunkedEncoder
	 */
	static public $_encoder;

	/**
	 * @param StreamObject $source
	 * 
	 * @return StreamObject
	 */
	public static function decode ($source) {
		return Chunked::decoder()->transform($source);
	}

	/**
	 * @return ChunkedDecoder
	 */
	public static function decoder () {
		if (Chunked::$_decoder === null) {
			Chunked::$_decoder = new ChunkedDecoder();
		}
		return Chunked::$_decoder;
	}

	/**
	 * @param StreamObject $source
	 * 
	 * @return StreamObject
	 */
	public static function encode ($source) {
		return Chunked::encoder()->transform($source);
	}

	/**
	 * @return ChunkedEncoder
	 */
	public static function encoder () {
		if (Chunked::$_encoder === null) {
			Chunked::$_encoder = new ChunkedEncoder();
		}
		return Chunked::$_encoder;
	}
}

Boot::registerClass(Chunked::class, 'tink.http.Chunked');
