<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\http;

use \php\Boot;
use \tink\core\FutureObject;

interface ClientObject {
	/**
	 *  Performs an HTTP(s) request
	 *  @param req - The HTTP request
	 *  @return The HTTP response
	 * 
	 * @param OutgoingRequest $req
	 * 
	 * @return FutureObject
	 */
	public function request ($req) ;
}

Boot::registerClass(ClientObject::class, 'tink.http.ClientObject');
