<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\http;

use \php\Boot;

class RequestHeader extends Header {
	/**
	 * @var string
	 */
	public $method;
	/**
	 * @var string
	 */
	public $protocol;
	/**
	 * @var object
	 */
	public $url;

	/**
	 * @param string $method
	 * @param object $url
	 * @param string $protocol
	 * @param \Array_hx $fields
	 * 
	 * @return void
	 */
	public function __construct ($method, $url, $protocol, $fields) {
		if ($protocol === null) {
			$protocol = "HTTP/1.1";
		}
		$this->method = $method;
		$this->url = $url;
		$this->protocol = $protocol;
		parent::__construct($fields);
	}

	/**
	 * @param \Array_hx $fields
	 * 
	 * @return RequestHeader
	 */
	public function concat ($fields) {
		$tmp = $this->method;
		$tmp1 = $this->url;
		$tmp2 = $this->protocol;
		return new RequestHeader($tmp, $tmp1, $tmp2, $this->fields->concat($fields));
	}

	/**
	 * @return string
	 */
	public function toString () {
		$this1 = $this->url;
		return "" . ($this->method??'null') . " " . ((($this1->query === null ? $this1->path : ((($this1->path === null ? "null" : $this1->path))??'null') . "?" . ((($this1->query === null ? "null" : $this1->query))??'null')))??'null') . " " . ($this->protocol??'null') . "\x0D\x0A" . (parent::toString()??'null');
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(RequestHeader::class, 'tink.http.RequestHeader');
