<?php
/**
 * Generated by Haxe 4.1.2
 */

namespace thenshim;

use \php\Boot;

/**
 * Creates promises.
 *
 * This interface is intended for providing fallback implementations when
 * the target does not provide JavaScript-style promises.
 *
 * @see `Promise` for method documentation.
 */
interface PromiseFactory {
	/**
	 * @param mixed $reason
	 * 
	 * @return Thenable
	 */
	public function asRejected ($reason) ;

	/**
	 * @param mixed $object
	 * 
	 * @return Thenable
	 */
	public function asResolved ($object) ;

	/**
	 * @param \Closure $executor
	 * 
	 * @return Thenable
	 */
	public function make ($executor) ;
}

Boot::registerClass(PromiseFactory::class, 'thenshim.PromiseFactory');
