<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\semver\_Preview;

use \php\_Boot\HxAnon;
use \php\Boot;
use \tink\core\TypedError;
use \tink\core\Outcome;

final class Preview_Impl_ {

	/**
	 * @param string $s
	 * 
	 * @return Outcome
	 */
	public static function ofString ($s) {
		$__hx__switch = ($s);
		if ($__hx__switch === "alpha") {
			return Outcome::Success("alpha");
		} else if ($__hx__switch === "beta") {
			return Outcome::Success("beta");
		} else if ($__hx__switch === "rc") {
			return Outcome::Success("rc");
		} else {
			return Outcome::Failure(new TypedError(422, "" . ($s??'null') . " should be alpha | beta | rc", new HxAnon([
				"fileName" => "tink/semver/Preview.hx",
				"lineNumber" => 14,
				"className" => "tink.semver._Preview.Preview_Impl_",
				"methodName" => "ofString",
			])));
		}
	}
}

Boot::registerClass(Preview_Impl_::class, 'tink.semver._Preview.Preview_Impl_');
