<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\url\_Portion;

use \php\Boot;
use \haxe\NativeStackTrace;

final class Portion_Impl_ {

	/**
	 * @param string $v
	 * 
	 * @return string
	 */
	public static function _new ($v) {
		return $v;
	}

	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	public static function get_raw ($this1) {
		return $this1;
	}

	/**
	 * @param string $this
	 * 
	 * @return bool
	 */
	public static function isValid ($this1) {
		if ($this1 !== null) {
			try {
				\urldecode($this1);
				return true;
			} catch(\Throwable $_g) {
				NativeStackTrace::saveStack($_g);
				return false;
			}
		} else {
			return true;
		}
	}

	/**
	 * @param string $s
	 * 
	 * @return string
	 */
	public static function ofString ($s) {
		return ($s === null ? "" : \rawurlencode($s));
	}

	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	public static function stringly ($this1) {
		return Portion_Impl_::toString($this1);
	}

	/**
	 * @param string $this
	 * 
	 * @return string
	 */
	public static function toString ($this1) {
		if ($this1 === null) {
			return null;
		} else {
			try {
				return \urldecode($this1);
			} catch(\Throwable $_g) {
				NativeStackTrace::saveStack($_g);
				return "";
			}
		}
	}
}

Boot::registerClass(Portion_Impl_::class, 'tink.url._Portion.Portion_Impl_');
Boot::registerGetters('tink\\url\\_Portion\\Portion_Impl_', [
	'raw' => true
]);
