<?php
/**
 * Generated by Haxe 4.0.5
 */

namespace sys;

use \php\_Boot\HxAnon;
use \sys\_FileSystem\FileKind;
use \php\Boot;
use \php\_Boot\HxException;
use \haxe\io\Path;

/**
 * This class provides information about files and directories.
 * If `null` is passed as a file path to any function in this class, the
 * result is unspecified, and may differ from target to target.
 * See `sys.io.File` for the complementary file API.
 */
class FileSystem {
	/**
	 * Returns the full path of the file or directory specified by `relPath`,
	 * which is relative to the current working directory. The path doesn't
	 * have to exist.
	 * 
	 * @param string $relPath
	 * 
	 * @return string
	 */
	public static function absolutePath ($relPath) {
		if (Path::isAbsolute($relPath)) {
			return $relPath;
		}
		return Path::join(\Array_hx::wrap([
			\Sys::getCwd(),
			$relPath,
		]));
	}

	/**
	 * Creates a directory specified by `path`.
	 * This method is recursive: The parent directories don't have to exist.
	 * If the directory cannot be created, an exception is thrown.
	 * 
	 * @param string $path
	 * 
	 * @return void
	 */
	public static function createDirectory ($path) {
		clearstatcache(true, $path);
		if (!is_dir($path)) {
			mkdir($path, 493, true);
		}
	}

	/**
	 * Deletes the directory specified by `path`. Only empty directories can
	 * be deleted.
	 * If `path` does not denote a valid directory, or if that directory cannot
	 * be deleted, an exception is thrown.
	 * 
	 * @param string $path
	 * 
	 * @return void
	 */
	public static function deleteDirectory ($path) {
		rmdir($path);
	}

	/**
	 * Deletes the file specified by `path`.
	 * If `path` does not denote a valid file, or if that file cannot be
	 * deleted, an exception is thrown.
	 * 
	 * @param string $path
	 * 
	 * @return void
	 */
	public static function deleteFile ($path) {
		unlink($path);
	}

	/**
	 * Returns `true` if the file or directory specified by `path` exists.
	 * 
	 * @param string $path
	 * 
	 * @return bool
	 */
	public static function exists ($path) {
		clearstatcache(true, $path);
		return file_exists($path);
	}

	/**
	 * Returns the full path of the file or directory specified by `relPath`,
	 * which is relative to the current working directory. Symlinks will be
	 * followed and the path will be normalized.
	 * 
	 * @param string $relPath
	 * 
	 * @return string
	 */
	public static function fullPath ($relPath) {
		return (realpath($relPath) ?: null);
	}

	/**
	 * Returns `true` if the file or directory specified by `path` is a directory.
	 * If `path` is not a valid file system entry or if its destination is not
	 * accessible, an exception is thrown.
	 * 
	 * @param string $path
	 * 
	 * @return bool
	 */
	public static function isDirectory ($path) {
		clearstatcache(true, $path);
		return is_dir($path);
	}

	/**
	 * @param string $path
	 * 
	 * @return FileKind
	 */
	public static function kind ($path) {
		clearstatcache(true, $path);
		$kind = filetype($path);
		if ($kind === false) {
			throw new HxException("Failed to check file type " . ($path??'null'));
		}
		if ($kind === "dir") {
			return FileKind::kdir();
		} else if ($kind === "file") {
			return FileKind::kfile();
		} else {
			return FileKind::kother($kind);
		}
	}

	/**
	 * Returns the names of all files and directories in the directory specified
	 * by `path`. `"."` and `".."` are not included in the output.
	 * If `path` does not denote a valid directory, an exception is thrown.
	 * 
	 * @param string $path
	 * 
	 * @return \Array_hx
	 */
	public static function readDirectory ($path) {
		$list = new \Array_hx();
		$dir = opendir($path);
		$file = null;
		while (true) {
			$file = readdir($dir);
			if (!($file !== false)) {
				break;
			}
			if (($file !== ".") && ($file !== "..")) {
				$list->arr[$list->length] = $file;
				++$list->length;
			}
		}
		closedir($dir);
		return $list;
	}

	/**
	 * Renames/moves the file or directory specified by `path` to `newPath`.
	 * If `path` is not a valid file system entry, or if it is not accessible,
	 * or if `newPath` is not accessible, an exception is thrown.
	 * 
	 * @param string $path
	 * @param string $newPath
	 * 
	 * @return void
	 */
	public static function rename ($path, $newPath) {
		rename($path, $newPath);
	}

	/**
	 * Returns `FileStat` information for the file or directory specified by
	 * `path`.
	 * 
	 * @param string $path
	 * 
	 * @return object
	 */
	public static function stat ($path) {
		clearstatcache(true, $path);
		$info = stat($path);
		if ($info === false) {
			throw new HxException("Unable to stat " . ($path??'null'));
		}
		$info1 = $info;
		$tmp = \Date::fromTime($info1["atime"] * 1000);
		$tmp1 = \Date::fromTime($info1["mtime"] * 1000);
		$tmp2 = \Date::fromTime($info1["ctime"] * 1000);
		return new HxAnon([
			"gid" => $info1["gid"],
			"uid" => $info1["uid"],
			"atime" => $tmp,
			"mtime" => $tmp1,
			"ctime" => $tmp2,
			"dev" => $info1["dev"],
			"ino" => $info1["ino"],
			"nlink" => $info1["nlink"],
			"rdev" => $info1["rdev"],
			"size" => $info1["size"],
			"mode" => $info1["mode"],
		]);
	}
}

Boot::registerClass(FileSystem::class, 'sys.FileSystem');
