<?php
/**
 * Generated by Haxe 4.1.2
 */

namespace haxe\iterators;

use \php\_Boot\HxAnon;
use \php\Boot;
use \haxe\IMap;

/**
 * This Key/Value iterator can be used to iterate across maps.
 */
class MapKeyValueIterator {
	/**
	 * @var object
	 */
	public $keys;
	/**
	 * @var IMap
	 */
	public $map;

	/**
	 * @param IMap $map
	 * 
	 * @return void
	 */
	public function __construct ($map) {
		$this->map = $map;
		$this->keys = $map->keys();
	}

	/**
	 * See `Iterator.hasNext`
	 * 
	 * @return bool
	 */
	public function hasNext () {
		return $this->keys->hasNext();
	}

	/**
	 * See `Iterator.next`
	 * 
	 * @return object
	 */
	public function next () {
		$key = $this->keys->next();
		return new HxAnon([
			"value" => $this->map->get($key),
			"key" => $key,
		]);
	}
}

Boot::registerClass(MapKeyValueIterator::class, 'haxe.iterators.MapKeyValueIterator');
