<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\querystring;

use \php\Boot;

class BuilderBase {
	/**
	 * @var mixed
	 */
	public $buffer;
}

Boot::registerClass(BuilderBase::class, 'tink.querystring.BuilderBase');
