<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\core;

use \php\Boot;

class MPair {
	/**
	 * @var mixed
	 */
	public $a;
	/**
	 * @var mixed
	 */
	public $b;

	/**
	 * @param mixed $a
	 * @param mixed $b
	 * 
	 * @return void
	 */
	public function __construct ($a, $b) {
		$this->a = $a;
		$this->b = $b;
	}
}

Boot::registerClass(MPair::class, 'tink.core.MPair');
