<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace tink\core;

use \php\Boot;

interface ProgressObject extends SignalObject, FutureObject {
}

Boot::registerClass(ProgressObject::class, 'tink.core.ProgressObject');
