<?php
/**
 * Generated by Haxe 4.0.5
 */

namespace haxe\ds;

use \php\Boot;

/**
 * A tree node of `haxe.ds.BalancedTree`.
 */
class TreeNode {
	/**
	 * @var int
	 */
	public $_height;
	/**
	 * @var mixed
	 */
	public $key;
	/**
	 * @var TreeNode
	 */
	public $left;
	/**
	 * @var TreeNode
	 */
	public $right;
	/**
	 * @var mixed
	 */
	public $value;

	/**
	 * @param TreeNode $l
	 * @param mixed $k
	 * @param mixed $v
	 * @param TreeNode $r
	 * @param int $h
	 * 
	 * @return void
	 */
	public function __construct ($l, $k, $v, $r, $h = -1) {
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:255: lines 255-264
		if ($h === null) {
			$h = -1;
		}
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:256: characters 3-11
		$this->left = $l;
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:257: characters 3-10
		$this->key = $k;
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:258: characters 3-12
		$this->value = $v;
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:259: characters 3-12
		$this->right = $r;
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:260: lines 260-263
		if ($h === -1) {
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 14-95
			$tmp = null;
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 15-32
			$_this = $this->left;
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 35-53
			$_this1 = $this->right;
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 14-95
			if ((($_this === null ? 0 : $_this->_height)) > (($_this1 === null ? 0 : $_this1->_height))) {
				#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 56-73
				$_this2 = $this->left;
				#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 14-95
				$tmp = ($_this2 === null ? 0 : $_this2->_height);
			} else {
				#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 76-94
				$_this3 = $this->right;
				#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 14-95
				$tmp = ($_this3 === null ? 0 : $_this3->_height);
			}
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:261: characters 4-99
			$this->_height = $tmp + 1;
		} else {
			#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:263: characters 4-15
			$this->_height = $h;
		}
	}

	/**
	 * @return string
	 */
	public function toString () {
		#C:\Program Files\Haxe\haxe\std/haxe/ds/BalancedTree.hx:270: characters 3-119
		return ((($this->left === null ? "" : ($this->left->toString()??'null') . ", "))??'null') . (("" . (\Std::string($this->key)??'null') . "=" . (\Std::string($this->value)??'null'))??'null') . ((($this->right === null ? "" : ", " . ($this->right->toString()??'null')))??'null');
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(TreeNode::class, 'haxe.ds.TreeNode');
