<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace haxe\macro;

use \php\Boot;

/**
 * Context provides an API for macro programming.
 * It contains common functions that interact with the macro interpreter to
 * query or set information. Other API functions are available in the tools
 * classes:
 * - `haxe.macro.ComplexTypeTools`
 * - `haxe.macro.ExprTools`
 * - `haxe.macro.TypeTools`
 */
class Context {
}

Boot::registerClass(Context::class, 'haxe.macro.Context');
