<?php
/**
 * Generated by Haxe 4.1.3
 */

namespace sys\io;

use \haxe\io\_BytesData\Container;
use \php\Boot;
use \haxe\io\Bytes;

/**
 * API for reading and writing files.
 * See `sys.FileSystem` for the complementary file system API.
 */
class File {
	/**
	 * Similar to `sys.io.File.write`, but appends to the file if it exists
	 * instead of overwriting its contents.
	 * 
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FileOutput
	 */
	public static function append ($path, $binary = true) {
		if ($binary === null) {
			$binary = true;
		}
		return new FileOutput(\fopen($path, ($binary ? "ab" : "a")));
	}

	/**
	 * Copies the contents of the file specified by `srcPath` to the file
	 * specified by `dstPath`.
	 * If the `srcPath` does not exist or cannot be read, or if the `dstPath`
	 * file cannot be written to, an exception is thrown.
	 * If the file at `dstPath` exists, its contents are overwritten.
	 * If `srcPath` or `dstPath` are null, the result is unspecified.
	 * 
	 * @param string $srcPath
	 * @param string $dstPath
	 * 
	 * @return void
	 */
	public static function copy ($srcPath, $dstPath) {
		\copy($srcPath, $dstPath);
	}

	/**
	 * Retrieves the binary content of the file specified by `path`.
	 * If the file does not exist or can not be read, an exception is thrown.
	 * `sys.FileSystem.exists` can be used to check for existence.
	 * If `path` is null, the result is unspecified.
	 * 
	 * @param string $path
	 * 
	 * @return Bytes
	 */
	public static function getBytes ($path) {
		$s = \file_get_contents($path);
		$tmp = \strlen($s);
		return new Bytes($tmp, new Container($s));
	}

	/**
	 * Retrieves the content of the file specified by `path` as a String.
	 * If the file does not exist or can not be read, an exception is thrown.
	 * `sys.FileSystem.exists` can be used to check for existence.
	 * If `path` is null, the result is unspecified.
	 * 
	 * @param string $path
	 * 
	 * @return string
	 */
	public static function getContent ($path) {
		return \file_get_contents($path);
	}

	/**
	 * Returns an `FileInput` handle to the file specified by `path`.
	 * If `binary` is true, the file is opened in binary mode. Otherwise it is
	 * opened in non-binary mode.
	 * If the file does not exist or can not be read, an exception is thrown.
	 * Operations on the returned `FileInput` handle read on the opened file.
	 * File handles should be closed via `FileInput.close` once the operation
	 * is complete.
	 * If `path` is null, the result is unspecified.
	 * 
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FileInput
	 */
	public static function read ($path, $binary = true) {
		if ($binary === null) {
			$binary = true;
		}
		return new FileInput(\fopen($path, ($binary ? "rb" : "r")));
	}

	/**
	 * Stores `bytes` in the file specified by `path` in binary mode.
	 * If the file cannot be written to, an exception is thrown.
	 * If `path` or `bytes` are null, the result is unspecified.
	 * 
	 * @param string $path
	 * @param Bytes $bytes
	 * 
	 * @return void
	 */
	public static function saveBytes ($path, $bytes) {
		$f = File::write($path);
		$f->write($bytes);
		$f->close();
	}

	/**
	 * Stores `content` in the file specified by `path`.
	 * If the file cannot be written to, an exception is thrown.
	 * If `path` or `content` are null, the result is unspecified.
	 * 
	 * @param string $path
	 * @param string $content
	 * 
	 * @return void
	 */
	public static function saveContent ($path, $content) {
		\file_put_contents($path, $content);
	}

	/**
	 * Similar to `sys.io.File.append`. While `append` can only seek or write
	 * starting from the end of the file's previous contents, `update` can
	 * seek to any position, so the file's previous contents can be
	 * selectively overwritten.
	 * 
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FileOutput
	 */
	public static function update ($path, $binary = true) {
		if ($binary === null) {
			$binary = true;
		}
		\clearstatcache(true, $path);
		if (!\file_exists($path)) {
			File::write($path)->close();
		}
		return new FileOutput(\fopen($path, ($binary ? "rb+" : "r+")));
	}

	/**
	 * Returns an `FileOutput` handle to the file specified by `path`.
	 * If `binary` is true, the file is opened in binary mode. Otherwise it is
	 * opened in non-binary mode.
	 * If the file cannot be written to, an exception is thrown.
	 * Operations on the returned `FileOutput` handle write to the opened file.
	 * If the file existed, its previous content is overwritten.
	 * File handles should be closed via `FileOutput.close` once the operation
	 * is complete.
	 * If `path` is null, the result is unspecified.
	 * 
	 * @param string $path
	 * @param bool $binary
	 * 
	 * @return FileOutput
	 */
	public static function write ($path, $binary = true) {
		if ($binary === null) {
			$binary = true;
		}
		return new FileOutput(\fopen($path, ($binary ? "wb" : "w")));
	}
}

Boot::registerClass(File::class, 'sys.io.File');
