<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace haxe;

use \php\Boot;

/**
 * Log primarily provides the `trace()` method, which is invoked upon a call to
 * `trace()` in Haxe code.
 */
class Log {
	/**
	 * @var \Closure
	 * Outputs `v` in a platform-dependent way.
	 * The second parameter `infos` is injected by the compiler and contains
	 * information about the position where the `trace()` call was made.
	 * This method can be rebound to a custom function:
	 * var oldTrace = haxe.Log.trace; // store old function
	 * haxe.Log.trace = function(v, ?infos) {
	 * // handle trace
	 * }
	 * ...
	 * haxe.Log.trace = oldTrace;
	 * If it is bound to null, subsequent calls to `trace()` will cause an
	 * exception.
	 */
	static public $trace;

	/**
	 * Format the output of `trace` before printing it.
	 * 
	 * @param mixed $v
	 * @param object $infos
	 * 
	 * @return string
	 */
	public static function formatOutput ($v, $infos) {
		$str = \Std::string($v);
		if ($infos === null) {
			return $str;
		}
		$pstr = ($infos->fileName??'null') . ":" . ($infos->lineNumber??'null');
		if ($infos->customParams !== null) {
			$_g = 0;
			$_g1 = $infos->customParams;
			while ($_g < $_g1->length) {
				$str = ($str??'null') . ", " . (\Std::string(($_g1->arr[$_g++] ?? null))??'null');
			}
		}
		return ($pstr??'null') . ": " . ($str??'null');
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$trace = function ($v, $infos = null) {
			echo((\Std::string(Log::formatOutput($v, $infos))??'null') . \PHP_EOL);
		};
	}
}

Boot::registerClass(Log::class, 'haxe.Log');
Log::__hx__init();
