<?php
/**
 * Generated by Haxe 4.1.2
 */

namespace haxe;

use \php\Boot;

class MainEvent {
	/**
	 * @var \Closure
	 */
	public $f;
	/**
	 * @var bool
	 * Tells if the event can lock the process from exiting (default:true)
	 */
	public $isBlocking;
	/**
	 * @var MainEvent
	 */
	public $next;
	/**
	 * @var float
	 */
	public $nextRun;
	/**
	 * @var MainEvent
	 */
	public $prev;
	/**
	 * @var int
	 */
	public $priority;

	/**
	 * @param \Closure $f
	 * @param int $p
	 * 
	 * @return void
	 */
	public function __construct ($f, $p) {
		$this->isBlocking = true;
		$this->f = $f;
		$this->priority = $p;
		$this->nextRun = \Math::$NEGATIVE_INFINITY;
	}

	/**
	 * Call the event. Will do nothing if the event has been stopped.
	 * 
	 * @return void
	 */
	public function call () {
		if ($this->f !== null) {
			($this->f)();
		}
	}

	/**
	 * Delay the execution of the event for the given time, in seconds.
	 * If t is null, the event will be run at tick() time.
	 * 
	 * @param float $t
	 * 
	 * @return void
	 */
	public function delay ($t) {
		$this->nextRun = ($t === null ? \Math::$NEGATIVE_INFINITY : microtime(true) + $t);
	}

	/**
	 * Stop the event from firing anymore.
	 * 
	 * @return void
	 */
	public function stop () {
		if ($this->f === null) {
			return;
		}
		$this->f = null;
		$this->nextRun = \Math::$NEGATIVE_INFINITY;
		if ($this->prev === null) {
			MainLoop::$pending = $this->next;
		} else {
			$this->prev->next = $this->next;
		}
		if ($this->next !== null) {
			$this->next->prev = $this->prev;
		}
	}
}

Boot::registerClass(MainEvent::class, 'haxe.MainEvent');
