<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace haxe;

use \php\Boot;

/**
 * Since not all platforms guarantee that `String` always uses UTF-8 encoding, you
 * can use this cross-platform API to perform operations on such strings.
 */
class Utf8 {
	/**
	 * @var string
	 */
	const enc = "UTF-8";

	/**
	 * @var string
	 */
	public $__b;

	/**
	 * Similar to `String.charCodeAt` but uses the UTF8 character position.
	 * 
	 * @param string $s
	 * @param int $index
	 * 
	 * @return int
	 */
	public static function charCodeAt ($s, $index) {
		return Utf8::uord(Utf8::sub($s, $index, 1));
	}

	/**
	 * Compare two UTF8 strings, character by character.
	 * 
	 * @param string $a
	 * @param string $b
	 * 
	 * @return int
	 */
	public static function compare ($a, $b) {
		return \strcmp($a, $b);
	}

	/**
	 * Decode an UTF8 string back to an ISO string.
	 * Throw an exception if a given UTF8 character is not supported by the decoder.
	 * 
	 * @param string $s
	 * 
	 * @return string
	 */
	public static function decode ($s) {
		return \utf8_decode($s);
	}

	/**
	 * Encode the input ISO string into the corresponding UTF8 one.
	 * 
	 * @param string $s
	 * 
	 * @return string
	 */
	public static function encode ($s) {
		return \utf8_encode($s);
	}

	/**
	 * Call the `chars` function for each UTF8 char of the string.
	 * 
	 * @param string $s
	 * @param \Closure $chars
	 * 
	 * @return void
	 */
	public static function iter ($s, $chars) {
		$len = Utf8::length($s);
		$_g = 0;
		while ($_g < $len) {
			$chars(Utf8::charCodeAt($s, $_g++));
		}
	}

	/**
	 * Returns the number of UTF8 chars of the String.
	 * 
	 * @param string $s
	 * 
	 * @return int
	 */
	public static function length ($s) {
		return \mb_strlen($s, "UTF-8");
	}

	/**
	 * This is similar to `String.substr` but the `pos` and `len` parts are considering UTF8 characters.
	 * 
	 * @param string $s
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return string
	 */
	public static function sub ($s, $pos, $len) {
		return \mb_substr($s, $pos, $len, "UTF-8");
	}

	/**
	 * @param int $i
	 * 
	 * @return string
	 */
	public static function uchr ($i) {
		return \mb_convert_encoding(\pack("N", $i), "UTF-8", "UCS-4BE");
	}

	/**
	 * @param string $s
	 * 
	 * @return int
	 */
	public static function uord ($s) {
		return \unpack("N", \mb_convert_encoding($s, "UCS-4BE", "UTF-8"))[1];
	}

	/**
	 * Tells if the String is correctly encoded as UTF8.
	 * 
	 * @param string $s
	 * 
	 * @return bool
	 */
	public static function validate ($s) {
		return \mb_check_encoding($s, "UTF-8");
	}

	/**
	 * Allocate a new Utf8 buffer using an optional bytes size.
	 * 
	 * @param int $size
	 * 
	 * @return void
	 */
	public function __construct ($size = null) {
		$this->__b = "";
	}

	/**
	 * Add the given UTF8 character code to the buffer.
	 * 
	 * @param int $c
	 * 
	 * @return void
	 */
	public function addChar ($c) {
		$tmp = $this;
		$tmp->__b = ($tmp->__b??'null') . (Utf8::uchr($c)??'null');
	}

	/**
	 * Returns the buffer converted to a String.
	 * 
	 * @return string
	 */
	public function toString () {
		return $this->__b;
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(Utf8::class, 'haxe.Utf8');
