<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\core\_Pair;

use \php\Boot;
use \tink\core\MPair;

final class Pair_Impl_ {

	/**
	 * @param mixed $a
	 * @param mixed $b
	 * 
	 * @return MPair
	 */
	public static function _new ($a, $b) {
		return new MPair($a, $b);
	}

	/**
	 * @param MPair $this
	 * 
	 * @return mixed
	 */
	public static function get_a ($this1) {
		return $this1->a;
	}

	/**
	 * @param MPair $this
	 * 
	 * @return mixed
	 */
	public static function get_b ($this1) {
		return $this1->b;
	}

	/**
	 * @param MPair $this
	 * 
	 * @return bool
	 */
	public static function isNil ($this1) {
		return $this1 === null;
	}

	/**
	 * @return MPair
	 */
	public static function nil () {
		return null;
	}

	/**
	 * @param MPair $this
	 * 
	 * @return bool
	 */
	public static function toBool ($this1) {
		return $this1 !== null;
	}
}

Boot::registerClass(Pair_Impl_::class, 'tink.core._Pair.Pair_Impl_');
Boot::registerGetters('tink\\core\\_Pair\\Pair_Impl_', [
	'b' => true,
	'a' => true
]);
