<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace php\net;

use \php\Boot;

class SslSocket extends Socket {
	/**
	 * @return void
	 */
	public function __construct () {
		parent::__construct();
		$this->protocol = "ssl";
	}
}

Boot::registerClass(SslSocket::class, 'php.net.SslSocket');
