<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace sys\db\_Mysql;

use \php\Boot;

class WriteMysqlResultSet extends MysqlResultSet {
	/**
	 * @var int
	 */
	public $affectedRows;

	/**
	 * @param int $affectedRows
	 * 
	 * @return void
	 */
	public function __construct ($affectedRows) {
		$this->affectedRows = 0;
		parent::__construct(null);
		$this->affectedRows = $affectedRows;
	}

	/**
	 * @return void
	 */
	public function fetchNext () {
	}

	/**
	 * @return int
	 */
	public function get_length () {
		return $this->affectedRows;
	}

	/**
	 * @return int
	 */
	public function get_nfields () {
		return 0;
	}

	/**
	 * @return bool
	 */
	public function hasNext () {
		return false;
	}
}

Boot::registerClass(WriteMysqlResultSet::class, 'sys.db._Mysql.WriteMysqlResultSet');
