<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace sys\db;

use \php\Boot;
use \sys\db\_Mysql\MysqlConnection;

class Mysql {
	/**
	 * @param object $params
	 * 
	 * @return Connection
	 */
	public static function connect ($params) {
		return new MysqlConnection($params);
	}
}

Boot::registerClass(Mysql::class, 'sys.db.Mysql');
