<?php
/**
 * Generated by Haxe 4.1.4
 */

use \sys\io\FileInput;
use \php\Boot;
use \haxe\io\Output;
use \php\Lib;
use \sys\io\FileOutput;
use \haxe\io\Input;
use \php\_Boot\HxString;
use \haxe\ds\StringMap;
use \haxe\SysTools;

/**
 * This class provides access to various base functions of system platforms.
 * Look in the `sys` package for more system APIs.
 */
class Sys {
	/**
	 * @var string
	 */
	static public $_programPath;
	/**
	 * @var mixed
	 * Environment variables set by `Sys.putEnv()`
	 */
	static public $customEnvVars;

	/**
	 * Returns all the arguments that were passed in the command line.
	 * This does not include the interpreter or the name of the program file.
	 * (java)(eval) On Windows, non-ASCII Unicode arguments will not work correctly.
	 * (cs) Non-ASCII Unicode arguments will not work correctly.
	 * 
	 * @return \Array_hx
	 */
	public static function args () {
		if (array_key_exists("argv", $_SERVER)) {
			return \Array_hx::wrap(array_slice($_SERVER["argv"], 1));
		} else {
			return new \Array_hx();
		}
	}

	/**
	 * Runs the given command. The command output will be printed to the same output as the current process.
	 * The current process will block until the command terminates.
	 * The return value is the exit code of the command (usually `0` indicates no error).
	 * Command arguments can be passed in two ways:
	 * 1. Using `args` to pass command arguments. Each argument will be automatically quoted and shell meta-characters will be escaped if needed.
	 * `cmd` should be an executable name that can be located in the `PATH` environment variable, or a full path to an executable.
	 * 2. When `args` is not given or is `null`, command arguments can be appended to `cmd`. No automatic quoting/escaping will be performed. `cmd` should be formatted exactly as it would be when typed at the command line.
	 * It can run executables, as well as shell commands that are not executables (e.g. on Windows: `dir`, `cd`, `echo` etc).
	 * Use the `sys.io.Process` API for more complex tasks, such as background processes, or providing input to the command.
	 * 
	 * @param string $cmd
	 * @param \Array_hx $args
	 * 
	 * @return int
	 */
	public static function command ($cmd, $args = null) {
		if ($args !== null) {
			if (Sys::systemName() === "Windows") {
				$_g = new \Array_hx();
				$_g1 = 0;
				$_g2 = (\Array_hx::wrap([\StringTools::replace($cmd, "/", "\\")]))->concat($args);
				while ($_g1 < $_g2->length) {
					$x = SysTools::quoteWinArg(($_g2->arr[$_g1++] ?? null), true);
					$_g->arr[$_g->length++] = $x;
				}
				$cmd = $_g->join(" ");
			} else {
				$_this = (\Array_hx::wrap([$cmd]))->concat($args);
				$f = Boot::getStaticClosure(SysTools::class, 'quoteUnixArg');
				$result = [];
				$data = $_this->arr;
				$_g_current = 0;
				$_g_length = count($data);
				while ($_g_current < $_g_length) {
					$result[] = $f($data[$_g_current++]);
				}
				$cmd = \Array_hx::wrap($result)->join(" ");
			}
		}
		$result = Boot::deref(0);
		system($cmd, $result);
		return $result;
	}

	/**
	 * Gives the most precise timestamp value available (in seconds),
	 * but only accounts for the actual time spent running on the CPU for the current thread/process.
	 * 
	 * @return float
	 */
	public static function cpuTime () {
		return microtime(true) - $_SERVER["REQUEST_TIME"];
	}

	/**
	 * Returns all environment variables.
	 * 
	 * @return StringMap
	 */
	public static function environment () {
		$env = $_SERVER;
		$collection = Sys::$customEnvVars;
		foreach ($collection as $key => $value) {
			$env[$key] = $value;
		}
		return Lib::hashOfAssociativeArray($env);
	}

	/**
	 * Returns the path to the current executable that we are running.
	 * 
	 * @return string
	 */
	public static function executablePath () {
		return $_SERVER["SCRIPT_FILENAME"];
	}

	/**
	 * Exits the current process with the given exit code.
	 * (macro)(eval) Being invoked in a macro or eval context (e.g. with `-x` or `--run`) immediately terminates
	 * the compilation process, which also prevents the execution of any `--next` sections of compilation arguments.
	 * 
	 * @param int $code
	 * 
	 * @return void
	 */
	public static function exit ($code) {
		exit($code);
	}

	/**
	 * Reads a single input character from the standard input and returns it.
	 * Setting `echo` to `true` will also display the character on the output.
	 * 
	 * @param bool $echo
	 * 
	 * @return int
	 */
	public static function getChar ($echo) {
		$c = fgetc(STDIN);
		if ($c === false) {
			return 0;
		} else {
			if ($echo) {
				echo($c);
			}
			return ord($c);
		}
	}

	/**
	 * Gets the current working directory (usually the one in which the program was started).
	 * 
	 * @return string
	 */
	public static function getCwd () {
		$cwd = getcwd();
		if ($cwd === false) {
			return null;
		}
		$l = mb_substr($cwd, -1, null);
		return ($cwd??'null') . (((($l === "/") || ($l === "\\") ? "" : "/"))??'null');
	}

	/**
	 * Returns the value of the given environment variable, or `null` if it
	 * doesn't exist.
	 * 
	 * @param string $s
	 * 
	 * @return string
	 */
	public static function getEnv ($s) {
		$value = getenv($s);
		if ($value === false) {
			return null;
		} else {
			return $value;
		}
	}

	/**
	 * Prints any value to the standard output.
	 * 
	 * @param mixed $v
	 * 
	 * @return void
	 */
	public static function print ($v) {
		echo(\Std::string($v));
	}

	/**
	 * Prints any value to the standard output, followed by a newline.
	 * On Windows, this function outputs a CRLF newline.
	 * LF newlines are printed on all other platforms.
	 * 
	 * @param mixed $v
	 * 
	 * @return void
	 */
	public static function println ($v) {
		echo((\Std::string($v)??'null') . PHP_EOL);
	}

	/**
	 * Returns the absolute path to the current program file that we are running.
	 * Concretely, for an executable binary, it returns the path to the binary.
	 * For a script (e.g. a PHP file), it returns the path to the script.
	 * 
	 * @return string
	 */
	public static function programPath () {
		return Sys::$_programPath;
	}

	/**
	 * Sets the value of the given environment variable.
	 * (java) This functionality is not available on Java; calling this function will throw.
	 * 
	 * @param string $s
	 * @param string $v
	 * 
	 * @return void
	 */
	public static function putEnv ($s, $v) {
		Sys::$customEnvVars[$s] = "" . ($v??'null');
		putenv("" . ($s??'null') . "=" . ($v??'null'));
	}

	/**
	 * Changes the current working directory.
	 * (java) This functionality is not available on Java; calling this function will throw.
	 * 
	 * @param string $s
	 * 
	 * @return void
	 */
	public static function setCwd ($s) {
		chdir($s);
	}

	/**
	 * Changes the current time locale, which will affect `DateTools.format` date formating.
	 * Returns `true` if the locale was successfully changed.
	 * 
	 * @param string $loc
	 * 
	 * @return bool
	 */
	public static function setTimeLocale ($loc) {
		return setlocale(LC_TIME, $loc) !== false;
	}

	/**
	 * Suspends execution for the given length of time (in seconds).
	 * 
	 * @param float $seconds
	 * 
	 * @return void
	 */
	public static function sleep ($seconds) {
		usleep((int)(($seconds * 1000000)));
	}

	/**
	 * Returns the standard error of the process, to which program errors can be written.
	 * 
	 * @return Output
	 */
	public static function stderr () {
		return new FileOutput((defined("STDERR") ? STDERR : fopen("php://stderr", "w")));
	}

	/**
	 * Returns the standard input of the process, from which user input can be read.
	 * Usually it will block until the user sends a full input line.
	 * See `getChar` for an alternative.
	 * 
	 * @return Input
	 */
	public static function stdin () {
		return new FileInput((defined("STDIN") ? STDIN : fopen("php://stdin", "r")));
	}

	/**
	 * Returns the standard output of the process, to which program output can be written.
	 * 
	 * @return Output
	 */
	public static function stdout () {
		return new FileOutput((defined("STDOUT") ? STDOUT : fopen("php://stdout", "w")));
	}

	/**
	 * Returns the type of the current system. Possible values are:
	 * - `"Windows"`
	 * - `"Linux"`
	 * - `"BSD"`
	 * - `"Mac"`
	 * 
	 * @return string
	 */
	public static function systemName () {
		$s = php_uname("s");
		$p = HxString::indexOf($s, " ");
		if ($p >= 0) {
			return mb_substr($s, 0, $p);
		} else {
			return $s;
		}
	}

	/**
	 * Gives the most precise timestamp value available (in seconds).
	 * 
	 * @return float
	 */
	public static function time () {
		return microtime(true);
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$customEnvVars = [];
		self::$_programPath = (realpath($_SERVER["SCRIPT_FILENAME"]) ?: null);
	}
}

Boot::registerClass(Sys::class, 'Sys');
Sys::__hx__init();
