<?php
/**
 * Generated by Haxe 4.1.5
 */

namespace tink\http\clients;

use \php\Boot;

class SecureCurlClient extends CurlClient {
	/**
	 * @param \Closure $curl
	 * 
	 * @return void
	 */
	public function __construct ($curl = null) {
		parent::__construct($curl);
		$this->protocol = "https";
	}
}

Boot::registerClass(SecureCurlClient::class, 'tink.http.clients.SecureCurlClient');
