<?php
/**
 * Generated by Haxe 4.1.4
 */

namespace tink\io\_Worker;

use \tink\core\_Lazy\LazyObject;
use \php\Boot;
use \tink\io\WorkerObject;
use \tink\core\FutureObject;

final class Worker_Impl_ {
	/**
	 * @var WorkerObject
	 */
	static public $EAGER;
	/**
	 * @var \Array_hx
	 */
	static public $pool;

	/**
	 * @param WorkerObject $this
	 * 
	 * @return WorkerObject
	 */
	public static function ensure ($this1) {
		if ($this1 === null) {
			return Worker_Impl_::get();
		} else {
			return $this1;
		}
	}

	/**
	 * @return WorkerObject
	 */
	public static function get () {
		$x = Worker_Impl_::$pool->length;
		return (Worker_Impl_::$pool->arr[($x <= 1 ? 0 : \mt_rand(0, $x - 1))] ?? null);
	}

	/**
	 * @param WorkerObject $this
	 * @param LazyObject $task
	 * 
	 * @return FutureObject
	 */
	public static function work ($this1, $task) {
		return $this1->work($task);
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$EAGER = new EagerWorker();
		self::$pool = \Array_hx::wrap([Worker_Impl_::$EAGER]);
	}
}

Boot::registerClass(Worker_Impl_::class, 'tink.io._Worker.Worker_Impl_');
Worker_Impl_::__hx__init();
